- src/app/paginas/historico/historico.component.html
- src/app/paginas/historico/historico.component.spec.ts
- src/app/paginas/historico/historico.component.ts
- src/app/paginas/home/home.component.html
- src/app/paginas/home/home.component.spec.ts
- src/app/paginas/home/home.component.ts
- src/app/paginas/login/login.component.html
- src/app/paginas/login/login.component.spec.ts
- src/app/paginas/login/login.component.ts
Eu adicionei as pastas que vamos usar no projeto.
> feature100: add pastes

- angular.json
- package-lock.json
- package.json
- src/app/componentes/user/user.component.html
- src/app/componentes/user/user.component.spec.ts
- src/app/componentes/user/user.component.ts
- src/app/paginas/historico/historico.component.html
- src/app/paginas/historico/historico.component.spec.ts
- src/app/paginas/historico/historico.component.ts
- src/app/paginas/home/home.component.html
- src/app/paginas/home/home.component.spec.ts
- src/app/paginas/home/home.component.ts
- src/app/paginas/login/login.component.html
- src/app/paginas/login/login.component.spec.ts
- src/app/paginas/login/login.component.ts
- src/app/pipe/moedas.pipe.spec.ts
- src/app/pipe/moedas.pipe.ts
- src/app/seguranca/testando.guard.spec.ts
- src/app/seguranca/testando.guard.ts
- src/app/servicos/teste.service.spec.ts
- src/app/servicos/teste.service.ts
Adicionei algumas patas para ser exemplos e instalei o bootstrap e bootstrap icon
> Feature100: add bootstrap and bootstrap icon, add any files like exemple

- src/app/app.routes.ts
Criação das rotas para as pastas login, home e extrato
> feature101: configuração de rotas

- .github/CODEOWNERS
development: add file CODEOWNERS
> development: add file CODEOWNERS

- README.md
> Main: update readme

- src/app/paginas/extrato/content-extrato/content-extrato.component.css
- src/app/paginas/extrato/content-extrato/content-extrato.component.html
Feature108: Desenvolvimento do conteúdo de cada data do extrato. Configurado botão para carregar ou retirar da tela o conteúdo. Adicionado ícones para recebimentos.
> Feature108

- src/app/paginas/extrato/header-extrato/header-extrato.component.css
- src/app/paginas/extrato/header-extrato/header-extrato.component.html
> feature107: edit css and html

- src/app/paginas/extrato/extrato.component.css
- src/app/paginas/extrato/extrato.component.html
- src/app/paginas/extrato/extrato.component.ts
feature107: add footer for mobile
> feature107: add footer for mobile

- src/app/paginas/extrato/extrato.component.css
- src/app/paginas/extrato/extrato.component.html
- src/app/paginas/extrato/extrato.component.ts
feature107: edit the footer to forrter-mobile
> feature107: edit the footer to forrter-mobile

- src/app/componentes/footer/footer-mobile/footer-mobile.component.css
- src/app/componentes/footer/footer-mobile/footer-mobile.component.html
Feature109: edit footer mobile
> Feature109: edit footer mobile

- src/app/componentes/footer/footer-mobile/footer-mobile.component.css
- src/app/componentes/footer/footer-mobile/footer-mobile.component.html
feature109: edit css and add div in html
> feature109: edit css and add div in html

- src/app/componentes/footer/footer-desktop/footer-desktop.component.css
- src/app/componentes/footer/footer-desktop/footer-desktop.component.html
- src/app/componentes/footer/footer-desktop/footer-desktop.component.spec.ts
- src/app/componentes/footer/footer-desktop/footer-desktop.component.ts
feature109: create footer-desktop
> feature109: create footer-desktop

- src/app/paginas/extrato/extrato.component.html
- src/app/paginas/extrato/extrato.component.ts
feature107: add footer-desktop
> feature107: add footer-desktop

- src/app/app.routes.ts
- src/app/paginas/cadastro/cadastro-mobile/cadastro-mobile.component.html
- src/app/paginas/cadastro/cadastro-mobile/cadastro-mobile.component.spec.ts
- src/app/paginas/cadastro/cadastro-mobile/cadastro-mobile.component.ts
- src/app/paginas/cadastro/cadastro.component.html
- src/app/paginas/cadastro/cadastro.component.spec.ts
- src/app/paginas/cadastro/cadastro.component.ts
feature100: add folder cadastro and add route cadastro
> feature100: add folder cadastro and add route cadastro

- src/app/componentes/navbar/navbar-mobile/navbar-mobile.component.css
- src/app/componentes/navbar/navbar-mobile/navbar-mobile.component.html
- src/app/componentes/navbar/navbar-mobile/navbar-mobile.component.spec.ts
- src/app/componentes/navbar/navbar-mobile/navbar-mobile.component.ts
feature114: create navbar mobile
> feature114: create navbar mobile

- src/app/paginas/extrato/extrato.component.html
- src/app/paginas/extrato/extrato.component.ts
- src/app/paginas/extrato/header-extrato/header-extrato.component.html
feature107: add navbar mobile and desktop
> feature107: add navbar mobile and desktop

- src/app/componentes/navbar/navbar-desktop/navbar-desktop.component.css
- src/app/componentes/navbar/navbar-desktop/navbar-desktop.component.html
> feature114: edit nav desktop

- src/app/paginas/extrato/header-extrato/header-extrato.component.css
feature107: display none at desktop header extato
> feature107: display none at desktop header extato

- src/app/paginas/extrato/content-extrato/content-extrato.component.html
Feature108: Alterado o height da tela.
> Feature108: Alterado o height da tela.

- src/app/paginas/extrato/header-extrato/header-extrato.component.css
> feature107: edit media query

- src/app/app.routes.ts
- src/app/componentes/navbar/navbar.component.html
- src/app/componentes/navbar/navbar.component.ts
- src/app/componentes/transacoes/deposito/deposito.component.css
- src/app/componentes/transacoes/deposito/deposito.component.html
- src/app/componentes/transacoes/deposito/deposito.component.spec.ts
- src/app/componentes/transacoes/deposito/deposito.component.ts
- src/app/componentes/transacoes/saque/saque.component.css
- src/app/componentes/transacoes/saque/saque.component.html
- src/app/componentes/transacoes/saque/saque.component.spec.ts
- src/app/componentes/transacoes/saque/saque.component.ts
- src/app/componentes/transacoes/transacoes.component.html
- src/app/componentes/transacoes/transacoes.component.spec.ts
- src/app/componentes/transacoes/transacoes.component.ts
- src/app/componentes/transacoes/transferencia/transferencia.component.css
- src/app/componentes/transacoes/transferencia/transferencia.component.html
- src/app/componentes/transacoes/transferencia/transferencia.component.spec.ts
- src/app/componentes/transacoes/transferencia/transferencia.component.ts
feature219: create transations page and them routes
> feature219: create transations page and them routes
